DM-46089: Add mosaic view for AuxTel camera
lsst-ts/rubintv pull request #213
Opened 2024-09-26 16:01 UTC by ugyballoons

The view can be accessed via the relative link [rubintv/tucson-usdf/auxtel/mosaic](url)

2024-10-11 19:29 UTC, sebastian-aranda requested changes
Sorry it took me so long to finish this review, I got distracted with several things in the way :dizzy_face:. Thanks for the efforts put here @ugyballoons , I left some comments, mostly suggestion, but anyways I ask you to take a look before merging please.

2024-10-11 19:29 UTC, sebastian-aranda commented on python/lsst/ts/rubintv/handlers/websocket_notifiers.py
> +        # logger.info("Sending updates to:", num_clients=len(clients_list))
Should this comment be removed?

2024-10-14 12:36 UTC, ugyballoons commented on python/lsst/ts/rubintv/models/models.py
> -    This class extends the Pydantic BaseModel to leverage data validation. It
Oops! That wasn't deliberate. I've replaced it and added the extra MosaicViewMeta property to the docs.

2024-10-14 12:37 UTC, ugyballoons commented on python/lsst/ts/rubintv/background/currentpoller.py
> +                # logger.info("Current - time taken:", elapsed=elapsed)
I've restored the logging

2024-10-14 12:52 UTC, ugyballoons commented on python/lsst/ts/rubintv/handlers/websocket.py
> +        return None
I looked this up as I understand one of the tenets of Python is `Explicit is better than implicit.`
[PEP-8](https://peps.python.org/pep-0008/#programming-recommendations) suggests not mixing `return` and `return something` in the same function, so I'll keep them in.

2024-10-17 13:57 UTC, merged